branches:
  only:
  - master

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::codecov(line_exclusions = list('R/plots.R', 'R/theme_nima.R', 'R/theme_jetblack.R', 'R/bioc.R', 'R/utilities.R'))"

notifications:
  email:
    on_success: change
    on_failure: change
